### ISSUE TITLE
[XSS] CodeViewer interprets HTML

### ISSUE THREAD

**Issue by marcelltoth** [stoplightio/ui-kit#164]
**Describe the bug**

A CodeViewer component will interpret the contents instead of simply rendering it.

**To Reproduce**

1. Instantiate a CodeViewer with the following props:
```json
{
  "className": "overflow-auto MV_block",
  "value": "<div>Hello world!</div>\n<img src=\"asd\" onerror=\"alert('dont do this')\" />",
  "language": null,
  "showLineNumbers": false
}
```
2. Render it.
3. Cry.

**Expected behavior**
It would render and highlight the HTML.

**Screenshots**
This is from the markdown-viewer storybook:
![image](https://user-images.githubusercontent.com/543372/82815922-dabe0c00-9ea2-11ea-95b1-6c870c7ac5dd.png)

**Comment by wmhilton** [comment]
@marcelltoth Would it make sense to duplicate or move the `useSanitizeHTML` hook from https://github.com/stoplightio/markdown-viewer/pull/50 to `ui-kit`?

**Comment by marcelltoth** [comment]
> 
> 
> @marcelltoth Would it make sense to duplicate or move the `useSanitizeHTML` hook from [stoplightio/markdown-viewer#50](https://github.com/stoplightio/markdown-viewer/pull/50) to `ui-kit`?

Sure, just make sure you move the optional `jsdom` dependency. I would really *move* it not *copy*, mdv imports from `ui-kit` anyway.

**Comment by marcelltoth** [comment]
Let's port this into `beta` somehow.

`git merge master` or whatever IDC, but let's make sure `beta` is not vulnerable.
